### ISSUE TITLE
Can't install via pip

### ISSUE THREAD

**Issue by Rudis1261** [samdixon/rust-rcon#1]
```
Collecting rust-rcon
  Could not find a version that satisfies the requirement rust-rcon (from versions: )
No matching distribution found for rust-rcon
```

Do you perhaps have instructions on getting this to work without pip? When I try and download the files and import them I get:

```
Traceback (most recent call last):
  File "./check.py", line 3, in <module>
    import rust_rcon
  File "/root/rcon/rust-rcon/rust_rcon/__init__.py", line 1, in <module>
    from . import command
  File "/root/rcon/rust-rcon/rust_rcon/command.py", line 53
    return f"{self.Message}, {self.Identifier}, {self.Type}, {self.Stacktrace}"
```

**Comment by samdixon** [comment]
Here you can try these instructions for installing without pip:
Clone the repo and run `python3 setup.py install && pip3 install -r requirements.txt`

That error may be an issue with your python version. This library requires 3.6 or greater. From my end this is a pretty immature library that was built for one specific use case. 

Let me know if I can help in any other way.

thanks!

sam

**Comment by Rudis1261** [comment]
Shot sam, I ended up using a simple socket to get the status of my server. I'm doing some particularly weird stuff by running a rust server in a container, so needed a replacement for the health check on the host
